### PR TITLE
Clone git repository as $user

### LINKED ISSUE #351: Warning: The directory '/srv/puppetboard/puppetboard' contains 1936 entries, which exceeds the default soft limit 1000
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.15.0, server 7.6.1
- Ruby: 2.7.5
- Distribution: Ubuntu 18.04.6 LTS
- Module version: 8.1.0

## How to reproduce (e.g Puppet code you use)
Thanks for a great module BTW.

puppet 7.6 or 7.6.1 or introduced a warning when a File resource affects more than 1000 files by default.  The puppetboard module trips over the limit and produces a warning because of the number of files in the puppetboard repository.

puppetboard/manifests/init.pp at line 224:

      file { "${basedir}/puppetboard":
        owner   => $user,
        recurse => true,
        require => Vcsrepo["${basedir}/puppetboard"],
        max_files => -1,
      }

max_files defaults to 0 (issues a warning). I added the attribute with a value -1 which disables the warning.  You might want to choose a different value, but that may cause the resource to fail at some later time when the files in the repo exceed the limit.

I have a slightly unusual puppetboard setup managed by puppet because I couldn't at the time figure out to make the puppetboard module manage the apache vhost with SSL certificate authentication.  The apache portion of the configuration is is not relevant to the warning but I've included it anyway.

    $ssl_dir = $::settings::ssldir
    $puppetboard_certname = $trusted['certname']
    class { 'puppetboard':
        manage_virtualenv => true,
        manage_git        => true,
        revision          => 'master',
        puppetdb_host     => 'puppetdb01.xxxxx.com',
        puppetdb_port     => 8081,
        puppetdb_key        => "${ssl_dir}/private_keys/${puppetboard_certname}.pem",
        puppetdb_ssl_verify => "${ssl_dir}/certs/ca.pem",
        puppetdb_cert       => "${ssl_dir}/certs/${puppetboard_certname}.pem",
        reports_count => 35,
        enable_catalog  => true,
        default_environment => 'production',
        extra_settings  => {
            'DAILY_REPORTS_CHART_DAYS' => '15',
            'TABLE_COUNT_SELECTOR' => '[10, 20, 50, 100, 500]',
            'GRAPH_TYPE' => '"pie"',
            'GRAPH_FACTS' => "['architecture', 'clientversion', 'domain',
                'lsbcodename', 'lsbdistcodename', 'lsbdistid',
                'lsbdistrelease', 'lsbmajdistrelease', 'netmask', 'osfamily',
                'puppetversion', 'processorcount', 'windows_product_name',
                'windows_release_id', 'windows_edition_id', 'kernelversion']"
        },
    }

    file { '/etc/ssl/certs/xxxxx_Certificate_Authority.pem':
        content => file('xxxxx_ssl/xxxxx_Certificate_Authority.pem'),
        notify  => Service['httpd'],
    }
    file { '/etc/ssl/certs/puppetboard-test.xxxxx.com.pem':
        content => file('xxxxxx_puppetboard/puppetboard-test.xxxxx.com.pem'),
        notify  => Service['httpd'],
    }
    file {'/etc/ssl/private/puppetboard-test.xxxxxx.com.key':
        content => file('xxxxx_puppetboard/puppetboard-test.xxxxx.com.key'),
        notify  => Service['httpd'],
    }
    class { 'apache':
        default_vhost => false,
    }
    class { 'apache::mod::wsgi':
        package_name    => 'libapache2-mod-wsgi-py3',
        mod_path        => '/usr/lib/apache2/modules/mod_wsgi.so',
    }
    apache::vhost { $trusted[certname]:
        vhost_name  => $trusted[certname],
        ip          => '192.168.1.131',
        port        => 443,
        docroot     => '/srv/puppetboard/puppetboard',

        wsgi_application_group  => 'puppetboard',
        wsgi_process_group      => 'puppetboard',
        wsgi_daemon_process     => 'puppetboard',
        wsgi_daemon_process_options => {
            python-home     => '/srv/puppetboard/virtenv-puppetboard',
            user            => 'puppetboard',
            processes       => 5,
            threads         => 25,
            display-name    => 'puppetboard',
        },
        wsgi_script_aliases => { '/' => '/srv/puppetboard/puppetboard/wsgi.py' },

        ssl                 =>  true,
        ssl_ca              => '/etc/ssl/certs/xxxxx_Certificate_Authority.pem',
        ssl_cert            => '/etc/ssl/certs/puppetboard-test.xxxxx.com.pem',
        ssl_key             => '/etc/ssl/private/puppetboard-test.xxxxx.com.key',
        ssl_options         => '+StdEnvVars',
        ssl_verify_client   => 'require',
        ssl_verify_depth    => 1,
    }

## What are you seeing

root@puppetdb01:/etc/puppetlabs/puppetdb/conf.d# puppet agent -t
Info: Using environment 'infrastructure'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for puppetdb01.xxxxxx.com
Info: Applying configuration version '1648231182'
Warning: The directory '/srv/puppetboard/puppetboard' contains 1936 entries, which exceeds the default soft limit 1000 and may cause excessive resource consumption and degraded performance. To remove this warning set a value for `max_files` parameter or consider using an alternate method to manage large directory trees

## What behaviour did you expect instead

No warning.

### PR DESCRIPTION
**Pull request by smortex**
Instead of cloning as root and using a file resource to change files
ownership to the configured user, directly clone the repository with
this user.

This fix a warning issued by puppet:
Warning: The directory '/srv/puppetboard/puppetboard' contains 1936 entries, which exceeds the default soft limit 1000

Fixes #351

### CODE REVIEW

**Review by kenyon — APPROVED** [review]

File: spec/acceptance/class_spec.rb [hunk 1]
```diff
@@ -2,7 +2,11 @@
 
 require 'spec_helper_acceptance'
 
-describe 'puppetboard class' do
+RSpec.configure do |c|
+  c.filter_run_excluding "broken_#{fact('os.name')}#{fact('os.release.major')}_puppet#{ENV['BEAKER_PUPPET_COLLECTION'].sub(%r{puppet}, '')}".downcase.to_sym => true
```
Comment (smortex) [inline spec/acceptance/class_spec.rb:6]: This `ENV['BEAKER_PUPPET_COLLECTION'].sub(%r{puppet}, '')` is awful, but `fact('puppetversion').split('.').first` seems not to be an option unfortunately.

**Review by kenyon — APPROVED** [review]

File: spec/acceptance/class_spec.rb (hunk 1 above)
Comment (ekohl) [reply spec/acceptance/class_spec.rb:6]: > `fact('puppetversion').split('.').first` seems not to be an option unfortunately.

I think `fact()` doesn't send `--puppet`. Perhaps it should be an option.

File: spec/acceptance/class_spec.rb [hunk 2]
```diff
@@ -2,7 +2,11 @@
...
+end
+
+describe 'puppetboard class', broken_debian11_puppet6: true do
```
Comment (ekohl) [inline spec/acceptance/class_spec.rb:9]: In most places we use `if:` or `unless:`, so:
```suggestion
describe 'puppetboard class', `unless: fact('os.name') == 'Debian' && `fact('os.release.major') == '11' do
```

For brevity I didn't specify the Puppet version.

Another thing to consider is what I did for theforeman-puppet: there's `unsupported_puppetserver` as a helper method: https://github.com/theforeman/puppet-puppet/blob/master/spec/support/acceptance/puppetserver.rb

Then we use `unless: unsupported_puppetserver` (https://github.com/theforeman/puppet-puppet/blob/84492f25379319c09d2fdcb26aa4e331fba4170c/spec/acceptance/puppetserver_latest_spec.rb#L3=).

Thinking more about it, perhaps it shouldn't be negatively named. So rather `if: has_puppetserver` instead. However, that's an implementation detail.

Comment (smortex) [reply spec/acceptance/class_spec.rb:9]: The Foreman approach looks gorgeous!  :heart:

File: spec/acceptance/class_spec.rb (hunk 1 above)
Comment (smortex) [reply spec/acceptance/class_spec.rb]: No more relevant now in support file.

File: spec/acceptance/support/puppetdb.rb [hunk 3]
```diff
@@ -0,0 +1,10 @@
+# frozen_string_literal: true
+
+def has_puppetdb
+  case host_inventory['facter']['os']['name']
+  when 'Debian'
+    return false if ENV['BEAKER_PUPPET_COLLECTION'] == 'puppet6' && host_inventory['facter']['os']['release']['major'] == '11'
+  end
+
+  true
+end
```
Comment (root-expert) [inline spec/acceptance/support/puppetdb.rb:10]: This should be `spec/support/acceptance/puppetdb.rb` :wink:

File: spec/setup_acceptance_node.pp [hunk 4]
```diff
@@ -0,0 +1,6 @@
+# Needed for facter to fetch facts used by the postgresql module
+if fact('os.name') == 'Ubuntu' and fact('os.release.full') == '18.04' {
```
Comment (root-expert) [inline spec/setup_acceptance_node.pp:2]: Instead of checking for ubuntu 18.04 we can check for Facter < 4, that way we won't install lsb-release on Puppet 7 which is not needed.

```ruby
if versioncmp($facts['facterversion'], '4.0.0') < 0
```

File: manifests/init.pp [hunk 5]
```diff
@@ -138,7 +138,7 @@
       vcsrepo { "${basedir}/puppetboard":
         ensure   => present,
         provider => git,
-        owner    => $user,
+        user     => $user,
```
Comment (bastelfreak) [inline manifests/init.pp:141]: will that break existing installations? was that maybe setup like that on purpose, so the user that runs it has no permissions / less permissions?

File: spec/acceptance/support/puppetdb.rb (hunk 3 above)
Comment (smortex) [reply spec/acceptance/support/puppetdb.rb:10]: I copied the pattern from the foreman example @ekohl liked to, I like the idea of isolating actual test code from support code that could be in a shared gem if it was used by more projects.

Would this cause trouble?

File: manifests/init.pp (hunk 5 above)
Comment (smortex) [reply manifests/init.pp:141]: The only case I can see is if the user cannot traverse one of the parent directories.

Because of https://github.com/voxpupuli/puppet-puppetboard/pull/349#pullrequestreview-872397712 I would also want to change this user to root:root by default, but I _this_ will be a breaking change

File: spec/setup_acceptance_node.pp [hunk 6]
```diff
@@ -0,0 +1,6 @@
+# Needed for facter to fetch facts used by the postgresql module
+if versioncmp($facts['facterversion'], '4.0.0') < 0 {
```
[the remark this answers is not in the document]
Comment (smortex) [reply spec/setup_acceptance_node.pp]: Only Debian 10 seems to install PuppetDB correctly with system postgresql: https://github.com/voxpupuli/puppet-puppetboard/actions/runs/2055526651

I adjusted the requirement to check for Ubuntu only…

[the remark this answers is not in the document]
Comment (ekohl) [reply spec/setup_acceptance_node.pp]: Interesting. I wonder if that's a bug in puppetlabs-puppetdb or a regression in puppetlabs-postgresql.

File: spec/acceptance/support/puppetdb.rb [hunk 7]
```diff
@@ -0,0 +1,10 @@
+# frozen_string_literal: true
+
+def has_puppetdb
+  case host_inventory['facter']['os']['name']
+  when 'Debian'
+    return false if ENV['BEAKER_PUPPET_COLLECTION'] == 'puppet6' && host_inventory['facter']['os']['release']['major'] == '11'
+  end
+
+  true
```
Comment (ekohl) [inline spec/acceptance/support/puppetdb.rb:9]: You can consider this style as well.
```suggestion
    ENV['BEAKER_PUPPET_COLLECTION'] != 'puppet6' && host_inventory['facter']['os']['release']['major'] != '11'
  else
    true
  end
```

**Review by ekohl — APPROVED** [review]
Feel free to merge or address the open comments. They're rather small style guides.

File: spec/acceptance/support/puppetdb.rb (hunk 7 above)
Comment (smortex) [reply spec/acceptance/support/puppetdb.rb:9]: The `&&` should also be changed to `||` but it feels less readable in my opinion so for now I will merge as is so that other PR can benefit from the fixes for Debian / Ubuntu.
